### ISSUE TITLE
BUG: ckicling on + and - when creating the atlas explodes the area of interest

### ISSUE THREAD

**Issue by severinmenard** [fieldpapers/fieldpapers#184] opened 2015-09-28 11:11 UTC
The old bug that appeared with v2 that many people noticed is still here: when clicking on + or - when creating the atlas, the area of interest for the future atlas becomes instantly a lot bigger and the user has to readjust again the area

**Comment by almccon** [comment] 2015-09-28 20:35
Is that the same bug as #142?

**Comment by sconnelley** [comment] 2015-10-13 23:20
@severinmenard  -- "+" or "-" meaning zoom controls or page add/remove controls?  If it's the zoom controls, what would be the appropriate behavior?  Not pinning the "area of interest" to the map? If that's the case, then this would be a bug but a feature request.

**Comment by severinmenard** [comment] 2015-10-13 23:33
page add/remove controls

**Comment by sconnelley** [comment] 2015-10-13 23:55
Thanks.  I just can't seem to repo this.  
Can you give me more details, ie: steps to reproduce, browser, etc...

**Comment by ian-ross** [comment] 2015-10-14 06:23
This is indeed a duplicate of #142 or something very much like it.  I've been able to replicate it by resizing the atlas page frame and clicking on the add/remove columns/rows buttons: I've put a screencast at https://vimeo.com/142347002 -- basically: hit the "zoom to fit" button, resize the atlas frame, add a column.  There's a PR in to fix it (https://github.com/fieldpapers/fp-web/pull/12) from someone who's a potential Outreachy intern at Cadasta.

**Comment by sconnelley** [comment] 2015-10-14 16:07
Thanks @ian-ross for the video, totally see the problem now.

**Comment by aawiseman** [comment] 2015-10-16 20:31
I was going to report this too, glad it's here!

**Comment by ian-ross** [comment] 2016-02-01 07:59
This should be fixed by https://github.com/fieldpapers/fp-web/pull/23

**Comment by ian-ross** [comment] 2016-03-01 14:12
This issue should be fixed or rendered obsolete by https://github.com/fieldpapers/fp-web/pull/23: if anyone thinks it's still a problem, please reopen this issue!

**Closed by ian-ross** 2016-03-01 14:12 UTC
