### ISSUE TITLE
Add labels to the Field Papers map

### ISSUE THREAD

**Issue by aawiseman** [fieldpapers/fieldpapers#247] opened 2016-04-07 21:28 UTC
Only the road names are showing up, would be good to have labels for POIs, buildings etc too. I think this may be a POSM only issue. @mojodna #

**Comment by almccon** [comment] 2016-04-07 21:38
Duplicate of https://github.com/AmericanRedCross/posm-carto/issues/11 and https://github.com/AmericanRedCross/posm-carto/issues/14?

**Closed by almccon** 2016-04-07 21:38 UTC
