### ISSUE TITLE
Adjust road widths on the map

### ISSUE THREAD

**Issue by aawiseman** [fieldpapers/fieldpapers#246] opened 2016-04-07 21:23 UTC
When doing some field mapping and using the OSM view (i.e. not satellite), people were confused about the roads -- because they're just a line, they were thinking the buildings were all too far away and were drawing them all closer to the road line, which would actually mean they were overlapping the actual road. Maybe the road line width can be adjusted to be wider each time you zoom in?

Compare the regular OSM to the Humanitarian view: 

![screen shot 2016-04-07 at 5 29 41 pm](https://cloud.githubusercontent.com/assets/5025092/14367500/64cbe1c8-fce6-11e5-9472-7f6f58a26b62.png)
![screen shot 2016-04-07 at 5 29 19 pm](https://cloud.githubusercontent.com/assets/5025092/14367501/64ce4cc4-fce6-11e5-825f-5e3322b51cbc.png)

**Comment by almccon** [comment] 2016-04-07 21:39
Duplicate of https://github.com/AmericanRedCross/posm-carto/issues/7

**Closed by almccon** 2016-04-07 21:39 UTC
