### ISSUE TITLE
Atlas with Imagery are black

### ISSUE THREAD

**Issue by severinmenard** [fieldpapers/fieldpapers#14] opened 2015-03-23 00:15 UTC
Eg: http://fieldpapers.org/files/prints/mhr72s3c/field-paper-mhr72s3c.pdf

Is there a reason? And a way to bypass this?

**Comment by danrademacher** [comment] 2015-03-23 20:43
@severinmenard, we're currently rebuilding the entire back end of the site, which will resolve this issue, but the replacement site doesn't launch for a few weeks yet. Until then, we don't have an immediate solution other than rerunning the atlas with fewer pages.

But when we go live with the rebuilt version, these problems should go away!

**Comment by mojodna** [comment] 2015-04-07 04:59
We determined that the usual cause for this is stamen/fieldpapers#325.  The work-around for that is to generate additional atlases of zoomed out areas to indirectly choose lower zooms.  This is fixed in the Rails port (although there are currently other reasons why it's not yet usable).

stamen/fieldpapers#299 includes some research on other causes (tl;dr: timeouts are handled poorly).  Since timeouts are the cause and the length of time it takes to render a page increases dramatically when source images time out, rather than rendering pages with black tiles, the render task will time out and the atlas won't be generated.

The slightly longer-term fix is to replace the PDF renderer w/ wkhtmltopdf, backed by Leaflet.  That way the timeout issues get deferred to WebKit, and we can use TileJSON to determine available zoom ranges.

I'm closing this, as it refers to the Rails port, and this is working there.

**Closed by mojodna** 2015-04-07 04:59 UTC
Labels: existingsite
