### ISSUE TITLE
Atlas generation failed

### ISSUE THREAD

**Issue by planemad** [fieldpapers/fieldpapers#84] opened 2015-05-05 07:56 UTC
Tried to create a single page PDF for my area in Bangalore using the Beta version, and it failed after waiting for around 10 minutes.

The url is here: http://next.fieldpapers.org/atlases/29531k5n

**Comment by mojodna** [comment] 2015-05-05 17:30
The root cause is probably #66, though it should have timed out much more quickly (timeouts are 30s and there was only 1 step).  This may have also coincided with an application restart, but that wouldn't have been necessary to cause this behavior.

That it wasn't displaying was resolved in https://github.com/fieldpapers/fp-web/commit/7f19576ef3c4ef717de42c36d4963af8d10be772

Thanks for reporting!

**Comment by mojodna** [comment] 2015-05-06 04:22
The implementation changed enough that this warrants closing.  Will keep an eye to see if application restarts are problematic.

**Closed by mojodna** 2015-05-06 04:22 UTC
